### ISSUE TITLE
Snyder

### ISSUE THREAD

**Issue by Snyder15** [rafaelvcaetano/melonDS-android#250] opened 2021-03-27 06:43 UTC
* **Device model:** SM-J200M
* **Android version:** Android API 22
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=/storage/extSdCard/Download/melonDS-beta APK - v1.3.0/Bios Melonds/Bios NDS/, dsiConfigDirectory=null/, internalDirectory=/data/data/me.magnum.melonds/files, fastForwardSpeedMultiplier=1.5, useJit=false, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Snyder, message=Hello!, language=5, favouriteColour=7, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/72AF-0A10%3ANintendo%20DS%2FMario%20Kart%20DS%20(USA)%20(En%2CFr%2CDe%2CEs%2CIt), romUri=content://com.android.externalstorage.documents/tree/72AF-0A10%3ANintendo%20DS%2FMario%20Kart%20DS%20(USA)%20(En%2CFr%2CDe%2CEs%2CIt)/document/72AF-0A10%3ANintendo%20DS%2FMario%20Kart%20DS%20(USA)%20(En%2CFr%2CDe%2CEs%2CIt)%2F0168%20-%20Mario%20Kart%20DS%20(USA)%20(En%2CFr%2CDe%2CEs%2CIt).nds, romPath=/storage/72AF-0A10/Nintendo DS/Mario Kart DS (USA) (En,Fr,De,Es,It)/0168 - Mario Kart DS (USA) (En,Fr,De,Es,It).nds, sramPath=/storage/72AF-0A10/Nintendo DS/Mario Kart DS (USA) (En,Fr,De,Es,It)/0168 - Mario Kart DS (USA) (En,Fr,De,Es,It).sav)
```

**Comment by rafaelvcaetano** [comment] 2021-03-27 17:08
Closed as duplicate of #251.

**Closed by rafaelvcaetano** 2021-03-27 17:08 UTC
