### ISSUE TITLE
Melonds Beta v1.3.0

### ISSUE THREAD

**Issue by moura464** [rafaelvcaetano/melonDS-android#221] opened 2021-03-20 13:00 UTC
![Screenshot_20210320-093854_melonDS](https://user-images.githubusercontent.com/22099440/111870347-0135c200-8963-11eb-9f04-f88aee25c717.jpg)
![Screenshot_20210320-093911_melonDS](https://user-images.githubusercontent.com/22099440/111870350-072ba300-8963-11eb-966a-38458c5589d3.jpg)
![Screenshot_20210320-094028_melonDS](https://user-images.githubusercontent.com/22099440/111870352-0b57c080-8963-11eb-93a9-a790a298cc33.jpg)

**Comment by rafaelvcaetano** [comment] 2021-03-21 01:44
Besides the low FPS, is there something wrong in the screenshots that I'm missing?

**Comment by shabbirmahmud** [comment] 2021-03-21 20:29
Duplicate of #142

**Comment by rafaelvcaetano** [comment] 2021-03-31 15:52
Closed due to lack of feedback.

**Closed by rafaelvcaetano** 2021-03-31 15:52 UTC
