### ISSUE TITLE
The work app issue but with log

### ISSUE THREAD

**Issue by GeekyG4mer** [rafaelvcaetano/melonDS-android#304] opened 2021-04-26 06:11 UTC
* **Device model:** POCO X2
* **Android version:** Android API 30
* **melonDS version:** Beta 1.5.0

**Problem:**  
I am the guy from issue #294 the issue is same, but the latest beta allowed me to upload the log so here it is.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://0%40com.android.externalstorage.documents/tree/01B6-1A11%3AGames%2FDs/document/01B6-1A11%3AGames%2FDs
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B(Unknown Source:128)
	at me.magnum.melonds.ui.emulator.k$e$a$a.a(Unknown Source:86)
	at f.a.c0.e.e.a.q(Unknown Source:10)
	at f.a.t.a(Unknown Source:14)
	at f.a.c0.e.b.e$a.d(Unknown Source:26)
	at f.a.c0.e.b.m$a.d(Unknown Source:2)
	at f.a.c0.e.b.k$a.run(Unknown Source:21)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/999/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:97:DF:18), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://0@com.android.externalstorage.documents/tree/01B6-1A11%3AGames%2FDs, romUri=content://0%40com.android.externalstorage.documents/tree/01B6-1A11%3AGames%2FDs/document/01B6-1A11%3AGames%2FDs%2FPokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E).zip, sramUri=null)
```

**Comment by GeekyG4mer** [comment] 2021-04-27 11:11
Is the log no help??

**Comment by rafaelvcaetano** [comment] 2021-04-27 11:13
It is because now I know where the problem is but I'm still not sure what's causing it. Do you already have an existing save file for that game?

**Comment by GeekyG4mer** [comment] 2021-04-27 12:36
>. Do you already have an existing save file for that game?


No

**Comment by rafaelvcaetano** [comment] 2021-04-27 13:02
Do you have one that you can use to make some tests?

**Comment by GeekyG4mer** [comment] 2021-04-28 06:06
> Do you have one that you can use to make some tests?

I tested with my heartgold rom with its save, it worked. Thanks and sorry for troubling. What experiments do you want? After that I will close both of these issues

**Comment by rafaelvcaetano** [comment] 2021-04-28 09:23
I want to know the following:
* Can you save and resume correctly?
* Can you use save states without crashing the app?

And don't close the issue please. There's clearly an problem that must be addressed.

**Comment by shabbirmahmud** [comment] 2021-04-28 11:24
> > Do you have one that you can use to make some tests?
> 
> I tested with my heartgold rom with its save, it worked. Thanks and sorry for troubling. What experiments do you want? After that I will close both of these issues

This is simmilar like #303

**Comment by GeekyG4mer** [comment] 2021-04-28 14:15
> I want to know the following:
> 
> * Can you save and resume correctly?

Yes
> * Can you use save states without crashing the app?

No
> 
> And don't close the issue please. There's clearly an problem that must be addressed.

Should I close #294 or should I keep both open

**Comment by rafaelvcaetano** [comment] 2021-04-28 14:17
Alright. This is helpful.

You can close the other issue.

**Comment by rafaelvcaetano** [comment] 2021-05-18 00:11
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2). I'm not sure if it will fix your problem in particular, but it's quite possible. Let me know how it goes.

**Comment by rafaelvcaetano** [comment] 2021-07-15 23:25
Closed due to lack of feedback.

**Closed by rafaelvcaetano** 2021-07-15 23:25 UTC
