### ISSUE TITLE
Enhancement: landscape mode support and screen repositioning features

### ISSUE THREAD

**Issue by tomrow** [rafaelvcaetano/melonDS-android#71] opened 2021-02-18 19:07 UTC
It would be nice to have landscape mode support on MelonDS, and the ability to reposition the screens like the Wii U virtual console emulator. I tried forcing it to landscape mode, but since it scales to the width of the screen, I could only partially see the DS calendar and clock, with everything else obscured.

**Comment by rafaelvcaetano** [comment] 2021-02-18 19:30
Customizable layouts are in development (but will still take a while), which will add support for landscape. However, in the next release, the display will adjust to always fit which should fix your problem when forcing landscape mode.

**Comment by rafaelvcaetano** [comment] 2021-02-26 12:32
The latest Beta 1.2.1 release should now display the screen properly when forcing the landscape orientation. It won't look pretty, but at least you will see the whole display. I will close this issue since it's a duplicate of #13. If you want to further discuss the layout customization feature, feel free to comment on [this discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions/113).

**Closed by rafaelvcaetano** 2021-02-26 12:32 UTC
