### ISSUE TITLE
Add Screen Resolution Scaling

### ISSUE THREAD

**Issue by klark231** [rafaelvcaetano/melonDS-android#1235] opened 2023-11-05 04:24 UTC
So I just tried Melon DS on PC and it look so much better on x4. you should also add resolution scaling

**Comment by Bruhmastra** [comment] 2023-11-05 05:45
I dont think rafael knows what resolution scaling means

**Comment by rafaelvcaetano** [comment] 2023-11-05 17:09
> I dont think rafael knows what resolution scaling means

Well, you have access to the source code of the app. You can try adding it yourself 🙂 

This is a duplicate of #559, so I'll close it to avoid having so many open issues.

**Closed by rafaelvcaetano** 2023-11-05 17:09 UTC
