### ISSUE TITLE
jr cannot launch the bios ds and dsi because of the error They tell me to come here who can help me please thank you in advance 

### ISSUE THREAD

**Issue by inazumarion** [rafaelvcaetano/melonDS-android#147] opened 2021-03-06 20:29 UTC
* **Device model:** Nokia 2.3
* **Android version:** Android API 29
* **melonDS version:** Beta 1.2.2

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_BAD
	at me.magnum.melonds.ui.emulator.h$c.a(Unknown Source:54)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=/storage/2722-1C15/Bios Melonds/Bios NDS/, dsiConfigDirectory=/storage/2722-1C15/Bios Melonds/Bios NDSi/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)))
```

**Comment by rafaelvcaetano** [comment] 2021-03-06 21:51
Closed because it's a duplicate of #146

**Closed by rafaelvcaetano** 2021-03-06 21:51 UTC
