### ISSUE TITLE
Porque meu fps fica baixo

### ISSUE THREAD

**Issue by berdo4** [rafaelvcaetano/melonDS-android#240] opened 2021-03-25 13:51 UTC
Celular J4 
![Screenshot_20210321-170807_melonDS](https://user-images.githubusercontent.com/81053272/112483654-01b1cc80-8d58-11eb-9ebf-2606078fd8f1.jpg)

**Comment by rafaelvcaetano** [comment] 2021-03-30 09:57
Closed as duplicate of #231.

**Closed by rafaelvcaetano** 2021-03-30 09:57 UTC
