### ISSUE TITLE
Request: will come on playstore?

### ISSUE THREAD

**Issue by lucariokalos** [rafaelvcaetano/melonDS-android#15] opened 2020-06-27 07:05 UTC
I want to see in playstore.

**Comment by rafaelvcaetano** [comment] 2020-06-27 13:10
Most likely. I still want to improve it a bit more though. The current performance level would leave a lot of users disappointed.

**Comment by lucariokalos** [comment] 2020-06-28 00:04
On future update will increase the speed?

**Comment by rafaelvcaetano** [comment] 2020-06-28 00:52
Eventually, yes.

**Comment by lucariokalos** [comment] 2020-06-28 04:00
First of all,need improve the speed then release on playstore.

**Comment by shabbirmahmud** [comment] 2021-03-14 06:50
Duplicate of #33

**Comment by rafaelvcaetano** [comment] 2021-08-05 19:58
melonDS is now available on the Play Store.

**Closed by rafaelvcaetano** 2021-08-05 19:58 UTC
