### ISSUE TITLE
Can't Load rom in 1.5.0.

### ISSUE THREAD

**Issue by Flamehere** [rafaelvcaetano/melonDS-android#303] opened 2021-04-26 05:46 UTC
* **Device model:** SM-A405FN
* **Android version:** Android API 29
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/msd%3A7004/document/msf%3A
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B(Unknown Source:128)
	at me.magnum.melonds.ui.emulator.k$e$a$a.a(Unknown Source:86)
	at f.a.c0.e.e.a.q(Unknown Source:10)
	at f.a.t.a(Unknown Source:14)
	at f.a.c0.e.b.e$a.d(Unknown Source:26)
	at f.a.c0.e.b.m$a.d(Unknown Source:2)
	at f.a.c0.e.b.k$a.run(Unknown Source:21)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:E7:57:20), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/msd%3A7004, romUri=content://com.android.providers.downloads.documents/tree/msd%3A7004/document/msf%3A7007, sramUri=null)
```

**Comment by shabbirmahmud** [comment] 2021-04-26 05:59
Duplicate of #297

**Comment by rafaelvcaetano** [comment] 2021-04-26 10:50
Are you using an SD card?

**Comment by Flamehere** [comment] 2021-04-26 10:54
No?i don't
![Uploading 20210426_125424.jpg…]()

**Comment by Flamehere** [comment] 2021-04-26 11:50
No

**Comment by Flamehere** [comment] 2021-04-26 11:53
listen i am not telling you to hurry, i just want you to tell me if i can this problem soon or it will take time, in the sense i am playing black pokemon 2 and if you tell me it will take time i will leave you alone

**Comment by rafaelvcaetano** [comment] 2021-04-26 12:48
OK. Lets try to speed this up. The problem is occurring when locating the save file. If you don't have a save file, the app will create one for you but it's failing. In all devices I have used until now to test this never happened so I need you to give me as much info as possible.

Do you already have an existing save file for the game you are trying to play?  
And to speed things up, I'm gonna ask you to give me the following:
- A screenshot of your Settings screen in the "Save Files" section
- A screen recording showing me were you have your ROM files and save files. The recording should start the moment you open your file explorer app so that I can see the exact path of those directories

**Comment by Flamehere** [comment] 2021-04-26 12:58
No?i don't use save file
2.ok
Screenshot 
![Screenshot_20210426-145234_melonDS](https://user-images.githubusercontent.com/83078875/116085729-646fee00-a69f-11eb-9295-1f1e602df200.jpg)
Video


Idk how send video 
Can t share your video

**Comment by rafaelvcaetano** [comment] 2021-04-26 12:59
You can upload files to GitHub.

**Comment by Flamehere** [comment] 2021-04-26 13:01
Il Lun 26 Apr 2021, 14:59 Rafael Caetano ***@***.***> ha
scritto:

**Comment by Flamehere** [comment] 2021-04-26 13:14
No i dont know how

**Comment by Flamehere** [comment] 2021-04-26 13:18
BROOOOO IT WORKS IT FINALLY WORKS NEVERMID THANKS!!!!!!!!!!

**Comment by rafaelvcaetano** [comment] 2021-04-26 13:35
Wait, what? What did you do to make it work?

**Comment by Flamehere** [comment] 2021-04-26 13:39
I converted my drastic save to 
.sav and then put in the roms carpet also
I disabled the "save next to rom file"

=
Pokemon Black2.nds
Pokemon Black2.sav
=

**Comment by Flamehere** [comment] 2021-04-26 13:40
But i cant use bios because the game crash but i dont give a fuck

**Comment by shabbirmahmud** [comment] 2021-04-26 16:49
> But i cant use bios because the game crash but i dont give a fuck

Is it generate log when crash like before?Can u give ur roms,save files and bios directory screenshot?

**Closed** 2021-04-26 17:59 UTC
