### ISSUE TITLE
Upscaling Resolution Option

### ISSUE THREAD

**Issue by hehk1234** [rafaelvcaetano/melonDS-android#1131] opened 2023-03-11 16:54 UTC
Hi, Good Night.

Please, add option to upscaling the resolution. I see original melonds windows have it. 

Many thanks for your support and time to bring this awesome work.

**Comment by Gamemulatorer** [comment] 2023-03-15 12:28
@hehk1234 duplicate of https://github.com/rafaelvcaetano/melonDS-android/issues/559

**Comment by rafaelvcaetano** [comment] 2023-11-05 17:29
As ghost said, it's a duplicate of #559. That feature is being worked on.

**Closed by rafaelvcaetano** 2023-11-05 17:29 UTC
