### ISSUE TITLE
the app restart when I try to load ds game

### ISSUE THREAD

**Issue by sogata-aw** [rafaelvcaetano/melonDS-android#52] opened 2021-02-02 07:46 UTC
i tried many time to lainch rom of different regions(USA, EU and JAP) but the app won't load it and restart. 

https://user-images.githubusercontent.com/75533495/106568123-2301f380-6533-11eb-91aa-e257f822385f.mp4

**Comment by rafaelvcaetano** [comment] 2021-02-02 14:03
This may possibly be a duplicate of #45. Could you give me the following info:
- Device name
- Android version
- Are you using a custom ROM?
- If you connect an external audio device (headphones or speakers) does the problem still persist?

**Comment by sogata-aw** [comment] 2021-02-02 18:14
i use a huawei
my android version is the 8.1
i'm trying to play original rom
and i didn't use headphones or speaker

**Comment by rafaelvcaetano** [comment] 2021-02-02 18:18
Do you have any headphones or speaker that you could connect to your phone? If so, could you connect it and try to open a ROM and see if it crashes? If you don't have any of that, we will try something else.

**Comment by sogata-aw** [comment] 2021-02-03 10:12
i have a huawei y7 2018
my android version is the 8.1 
i didn't used custom rom
and I didn't connect external audio advice

**Comment by sogata-aw** [comment] 2021-02-03 10:17
i tried to connect my headphones but it still crash

**Comment by rafaelvcaetano** [comment] 2021-02-03 14:24
I will need more information to find the problem. I will need you to do the following:
1. Install this version of melonDS: http://s000.tinyupload.com/?file_id=10936153351108951882
2. Enable USB debugging through the following steps:
    1. Go to Settings
    2. Go to “About device” (Might be named slightly different)
    3. Click the “Build number” field 7 times. This will turn on “Developer options”
    4. Go back to Settings
    5. Go to “Developer options”
    6. Scroll down and enable “USB debugging”
3. Download ADB (Android Debug Bridge) for your PC from [here](https://developer.android.com/studio/releases/platform-tools)
4. Extract the contents of the downloaded ZIP
5. Connect your device to your PC
6. Open a command line or terminal on your PC
7. Drag the file "platform-tools/adb" from the folder you extracted to the command line/terminal
9. Add the following text in the command line/terminal: ` logcat > log.txt`
    1. The final line should look like this: `<path_to_extracted_folder>/adb logcat > log.txt`
10. Press ENTER
11. You will see a pop-up on your device and click "Allow"
12. Open a ROM on your device and wait for it to crash
13. Once the app crashes, press Ctrl+C or Cmd+C in the command line/terminal
14. A file will appear in the directory displayed by the command line/terminal. Go to that folder, find the file named "log.txt" and send it to me

If you have any problem following these steps, let me know.

**Comment by sogata-aw** [comment] 2021-02-03 14:45
i found what was the problem,
it was because i used a usb for my roms.
but thank you very much for your help(sorry)

**Closed** 2021-02-04 19:11 UTC
