### ISSUE TITLE
Issue with work app

### ISSUE THREAD

**Issue by GeekyG4mer** [rafaelvcaetano/melonDS-android#294] opened 2021-04-21 02:19 UTC
I created a work version of melonds to play multiplayer in split screen but I am having issues with loading the roms ( maybe because of android 11)
**********************

* **Device model:** < POCO X2 >
* **Android version:** <MIUI 12(based on android 11)>

**Problem:**  
The work version of app cannot load roms either from sd card or storage/0 and the storage/999 cannot be selected because even the work version of app uses the personal android file manager.

**Steps to reproduce (if applicable):**
1. Create a dual/work version of melonds and try loading roms.

The screenshot says a log was generated but I don't know how to upload it here, my apologies. 
![Screenshot_2021-04-21-07-48-01-660_me magnum melonds](https://user-images.githubusercontent.com/82920075/115487242-eada9900-a275-11eb-948d-29413f4fb5df.jpg)

I am a normal user with no knowledge of coding but I think using a work version of file manager with the work version of melonds may fix the issue.

**Comment by shabbirmahmud** [comment] 2021-04-21 04:33
>The screenshot says a log was generated but I don't know how to upload it here, my apologies.

Click ok.Then u will come in github issu.Then publish that issu here.It will help to find the cause.

**Comment by GeekyG4mer** [comment] 2021-04-21 08:45
> > The screenshot says a log was generated but I don't know how to upload it here, my apologies.
> 
> Click ok.Then u will come in github issu(sign in github account).Then publish that issu here.It will help to find the cause.
> And make sure u are using beta v1.4.0.

**Comment by GeekyG4mer** [comment] 2021-04-21 08:46
After clicking ok, the emulator goes to rom selection page github doesn't open

**Comment by shabbirmahmud** [comment] 2021-04-21 08:51
> After clicking ok, the emulator goes to rom selection page github doesn't open

Maybe there is no default browser in ypur work profile.Clone any of your browser from personal profile.Then clear data the emulator and try again in clicking ok.

**Comment by GeekyG4mer** [comment] 2021-04-21 09:12
Is there any manual way to upload the log file?

**Comment by rafaelvcaetano** [comment] 2021-04-21 09:58
> Is there any manual way to upload the log file?

No. But check which app version you are using. You can check it by going to your device's Settings, go to Apps, find and click on melonDS, and you should see the app's version either under the app's name or at the bottom of the screen. If you're not using the Beta 1.4.0 release, please install that version.

**Comment by GeekyG4mer** [comment] 2021-04-21 11:31
> > Is there any manual way to upload the log file?
> 
> No. But check which app version you are using. You can check it by going to your device's Settings, go to Apps, find and click on melonDS, and you should see the app's version either under the app's name or at the bottom of the screen. If you're not using the Beta 1.4.0 release, please install that version.

I set up two browsers for work profile but nothing happens after I click ok and yes I am using beta 1.4.0

**Comment by shabbirmahmud** [comment] 2021-04-21 13:54
>The work version of app cannot load roms either from sd card or storage/0 and the storage/999 cannot be selected because even the work version of app uses the personal android file manager.

Are u saying that ur internal storage is same for both profile?(Personal/work)
What i know u can't use use external storage/sd card in work profile. But u can use internel storage which was created by the island apk that is different from personal profile internal storage.And there is a limitation to that internal storage too if u are using android 11. You wont be able to select download folder. But u can use rest of the folders.

> I set up two browsers for work profile but nothing happens after I click ok and yes I am using beta 1.4.0

Are u using custom bios or emulator internal bios?If you are using custom bios then send the screenshots of your bios directory from both file manager and emulator settings.And also send the screenshots of rom directory and which rom u was trying to load.

**Comment by GeekyG4mer** [comment] 2021-04-21 17:45
> > The work version of app cannot load roms either from sd card or storage/0 and the storage/999 cannot be selected because even the work version of app uses the personal android file manager.
> 
> Are u saying that ur internal storage is same for both profile?(Personal/work)
> What i know u can't use use external storage/sd card in work profile. But u can use internel storage which was created by the island apk that is different from personal profile internal storage.And there is a limitation to that internal storage too if u are using android 11. You wont be able to select download folder. But u can use rest of the folders.
> 
> > I set up two browsers for work profile but nothing happens after I click ok and yes I am using beta 1.4.0
> 
> Are u using custom bios or emulator internal bios?If you are using custom bios then send the screenshots of your bios directory from both file manager and emulator settings.And also send the screenshots of rom directory and which rom u was trying to load.

No I am aware that work profile have a separate storage(storage/999) and the problem is personal apps can't access it and the work melonds uses personal google files application. And I am using the emulator itself no firmware or bios.

**Comment by shabbirmahmud** [comment] 2021-04-22 04:34
>No I am aware that work profile have a separate storage(storage/999) and the problem is personal apps can't access it and the work melonds uses personal google files application. 

Oh u can't select that directories which island application was created. If you try to slelect that directory from melonds it don't redirect u to work profile file manager.It sends u to personal profile file manager?I guess there is a problem with ur island application.Island is still beta so problems can be occur.I didn't face this kind of problems with island.But u can try to delete ur work profile from android setting and resetup it.Then clone again and check if this problems occur again.

**Comment by GeekyG4mer** [comment] 2021-04-22 05:03
> > No I am aware that work profile have a separate storage(storage/999) and the problem is personal apps can't access it and the work melonds uses personal google files application.
> 
> Oh u can't select that directories which island application was created. If you try to slelect that directory from melonds it don't redirect u to work profile file manager.It sends u to personal profile file manager?Then u select that personal profile directories means two melonds using the same directory am i right?
> I guess there is a problem with ur island application.Island is still beta so problems can be occur.I didn't face this kind of problems with island.


No I am not using any third party apps to do this. This feature is in built in the os MIUI 12 as I stated, it creates a separate directory for work apps and work apps can only access that directory also only work apps can access the directory. The problem as I said before is that work profile of melonds is not using the work profile of file manager which is used to select directory.

**Comment by shabbirmahmud** [comment] 2021-04-22 05:30
>The problem as I said before is that work profile of melonds is not using the work profile of file manager which is used to select directory.

You are using miui 12 built in system cloner  ig.I used xioami system cloner.What i remember there will be a shared internal storage in the file manager which was created by system cloner.You can copy your rom and bios(if using) to that internal storage.Bt it seems to be melonds can't find that directory.Can u give a screenshot of ur file manager and which file manager open if you try to select the directory from cloned melonds?

**Comment by GeekyG4mer** [comment] 2021-04-22 06:31
> > The problem as I said before is that work profile of melonds is not using the work profile of file manager which is used to select directory.
> 
> You are using miui 12 built in system cloner/app cloner ig.I used xioami system cloner/app cloner once.What i remember there will be a shared internal storage in the file manager which was created by system cloner/app cloner.It's weird when i used i could also acess the main internal directory.There was no personal and work profile iirc.It was just a seperate space for cloned apps.
> 
> Is your main melonds can load the rom?If you are using same rom diectory for both melonds then you should copy your rom and bios(if using) to that internal storage from file manager.Maybe 2 emulator can't use the same rom directory.Bt it seems to be melonds can't find that directory.Can u give a screenshot of ur file manager and which file manager open if you try to select the directory from cloned melonds?Screen Recording the full step would be best.

Yes you can't see the work storage from system file manager because miui 12 is based on android 11 and it doesn't allow it. In MIUI 11 it was possible. My main melonds can load the roms and yes you are right, the work melonds can't find the roms as work apps can't access the personal internal storage. They can only access directories in storage/999 which I am unable to set the path to. I will post a screen recording after an hour or two.

**Comment by shabbirmahmud** [comment] 2021-04-22 09:39
Did your rom directory is same for both emulators?(Main and Cloned).If yes then create a different folder in your sd card and copy that rom in that folder.Then select that new folder from cloned melonds and check if this load?Probably two same emulators using same rom directory won't work.

**Comment by shabbirmahmud** [comment] 2021-04-22 09:45
I saw the screen recorder u sent.It's weird that u can actually select the personal profile directories from work profile application.It should be two different space and don't affect by others.Somthing is wrong with miui cloner and it's my first time seeing miui cloner creates two profile.Maybe thats why the rom is not loading.I would recommend u to use island apk and then clone the emulator.In island app u won't be able to select or affect your personal profile and vice versa.

**Comment by GeekyG4mer** [comment] 2021-04-22 11:10
> Did your rom directory is same for both emulators?(Main and Cloned).If yes then create a different folder in your sd card and copy that rom in that folder.Then select that new folder from cloned melonds and check if this load?Probably two same emulators using same rom directory won't work.

No the two apps use different directories

**Comment by GeekyG4mer** [comment] 2021-04-22 11:13
> I saw the screen recorder u sent.It's weird that u can actually select the personal profile directories from work profile application.It should be two different space and don't affect by others.Somthing is wrong with miui cloner and it's my first time seeing miui cloner creates two profile.Maybe thats why the rom is not loading.I would recommend u to use island apk and then clone the emulator.In island app u won't be able to select or affect your personal profile and vice versa.

I will wait till wifi multiplayer is added and if not then only I will do third party application. Thank you for your help. When will the next beta be released. Its already a month since the last update

**Comment by rafaelvcaetano** [comment] 2021-04-22 14:09
This release is taking more time because the new features I wanted to include are taking longer than expected. I want to release an update this weekend but there are still some problems that I need to fix and I'm not sure if it will be possible. If not, it should be released next week.

**Comment by shabbirmahmud** [comment] 2021-04-22 16:03
> if not then only I will do third party application. 

Let me know if third parties application can load the rom or not.

**Comment by shabbirmahmud** [comment] 2021-04-26 07:01
Duplicate of #304

**Closed** 2021-04-28 16:41 UTC
