### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#142] opened 2021-03-06 04:37 UTC
Can you fix lag please or atleast get 30fps please @rafaelvcaetano

**Comment by ASGAMING009** [comment] 2021-03-06 04:38
In Know Your A Busy Guy But Please

**Comment by shabbirmahmud** [comment] 2021-03-14 07:58
Yep compared to the drastic ds emulator melonds is very laggy.It needs more optimization.

Watch in this video-https://youtu.be/bmqV7P0dg-c

**Comment by shabbirmahmud** [comment] 2021-03-21 20:28
Duplicate of #231

**Comment by rafaelvcaetano** [comment] 2021-04-01 17:11
Sorry for not giving this issue any attention. There's nothing I can regarding performance right now but naturally, the performance should improve with time. So, keep trying the latest versions.

**Closed by rafaelvcaetano** 2021-04-01 17:11 UTC
