### ISSUE TITLE
Rom error

### ISSUE THREAD

**Issue by alwaysdimdim** [rafaelvcaetano/melonDS-android#79] opened 2021-02-21 09:08 UTC
![Screenshot_2021-02-21-15-29-49-76_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/79393179/108620474-fe78a780-745e-11eb-8dc5-f20e52ce54eb.jpg)
Why melonds white screen in my device

**Comment by rafaelvcaetano** [comment] 2021-02-21 12:53
I will need more info:
* In what mode are you running? DS or DSi? 
* Which game are you trying to run?

Additionally, could you get a screenshot of your Settings screen in the System section?

**Comment by alwaysdimdim** [comment] 2021-02-22 00:39
I tried to play Pokemon Heartgold and I sent the rest by email

**Comment by alwaysdimdim** [comment] 2021-02-23 13:57
Here?I'am running DS mode

Pada tanggal Min, 21 Feb 2021 19.53, Rafael Caetano <
notifications@github.com> menulis:

**Comment by rafaelvcaetano** [comment] 2021-02-23 14:07
Does this happen after loading the ROM? Or after playing for a while? I this happens immediately after loading the ROM, I suspect you have a faulty BIOS and/or firmware.

**Comment by alwaysdimdim** [comment] 2021-02-23 15:03
Yes, it is. this happened after loading the rom and I got the bios here:
https: //emulation.gametechwiki.com/index.php/Emulator_Files

Pada tanggal Sel, 23 Feb 2021 21.08, Rafael Caetano <
notifications@github.com> menulis:

**Comment by alwaysdimdim** [comment] 2021-02-23 15:18
Oh i use melonds beta1,0,0 because in latest version could not detect BIOS
when i try to set

Pada tanggal Sel, 23 Feb 2021 22.02, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by rafaelvcaetano** [comment] 2021-02-23 15:22
Does it work on the newest version?

**Comment by alwaysdimdim** [comment] 2021-02-23 15:48
Yeah i tried in melonds newest version

Pada tanggal Sel, 23 Feb 2021 22.46, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by alwaysdimdim** [comment] 2021-02-23 15:56
Pada tanggal Sel, 23 Feb 2021 22.47, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by alwaysdimdim** [comment] 2021-02-23 16:09
And this is my bios file

Pada tanggal Sel, 23 Feb 2021 22.56, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by rafaelvcaetano** [comment] 2021-02-23 17:26
Can you try a different BIOS?

**Comment by alwaysdimdim** [comment] 2021-02-24 05:26
yes I have tried several bios on the internet but only the one I screenshot
can

Pada tanggal Rab, 24 Feb 2021 00.26, Rafael Caetano <
notifications@github.com> menulis:

**Comment by rafaelvcaetano** [comment] 2021-02-24 10:33
Have you tried using other ROMs? If yes, do they work?

**Comment by shabbirmahmud** [comment] 2021-02-26 23:50
Try the new [beta v1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2) release and check if it's solve the problem?

**Comment by shabbirmahmud** [comment] 2021-03-01 18:55
I faced this white screen problem in my redmi 5 plus.It happened previous version of melonds.I can't remember which version.I was using ds mode abd the bios directory was in external storage.Then i tried to boot the rom and got this white screen.Bt when i turned off 'show boot screen' option the white screen problem was solved.

**Comment by shabbirmahmud** [comment] 2021-03-01 18:55
Try the new [beta v1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2) release and check if it's solve the problem?

**Comment by shabbirmahmud** [comment] 2021-03-13 09:34
Duplicate of #172

**Comment by shabbirmahmud** [comment] 2021-03-14 06:44
Can you use the latest beta [v1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.3.0) and open a new issue? The latest version does not fix the problem but includes additional info that will help to find the cause.

**Comment by rafaelvcaetano** [comment] 2021-03-28 23:38
Try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. There were some problems loading ROMs under certain emulator configurations and that should be fixed. I will close this issue for now but feel free to open a new one if the problem persists.

**Closed by rafaelvcaetano** 2021-03-28 23:38 UTC

**Comment by alwaysdimdim** [comment] 2021-03-29 01:58
Pada tanggal Sen, 29 Mar 2021 06.38, Rafael Caetano <
***@***.***> menulis:
