### ISSUE TITLE
Roms folder select bug

### ISSUE THREAD

**Issue by SuperLuigiGlitchy3** [rafaelvcaetano/melonDS-android#518] opened 2021-07-25 20:13 UTC
**Problem:**  
When I select a folder containing my roms, I get back to my phone menu, then when I try to comeback to the app, I get back again to my phone menu. Why I got this?

**Comment by Gamemulatorer** [comment] 2021-07-25 20:19
What is your phone android version?
Do you use external sscard?

**Comment by SuperLuigiGlitchy3** [comment] 2021-07-25 20:25
Android version: 9
No, I don't use external SD card.

**Comment by rafaelvcaetano** [comment] 2021-07-25 21:02
Which version of the emulator are you using? If you are not sure, try using the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2). If you are already using the latest version or if the problem is not fixed, could you record a video showing the problem?

**Comment by SuperLuigiGlitchy3** [comment] 2021-07-25 21:15
I'm using 1.5.2, and It worked finally, sorry for disturbing.

**Comment by XiaomiRedmi9** [comment] 2021-07-25 22:36
You can now close this...

**Closed** 2021-07-26 16:15 UTC
