### ISSUE TITLE
Can't load rom 

### ISSUE THREAD

**Issue by Flamehere** [rafaelvcaetano/melonDS-android#297] opened 2021-04-24 10:41 UTC
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:** <Samsung A40>
* **Android version:** <10>

**Problem:**  
When i try to load a rom it says "COULD NOT LOAD THIS ROM and error log was generated that can help to fix his problem".

**Steps to reproduce (if applicable):**
1. Write a list of steps
2. Required for the problem
3. To appear

Add screenshots if the issue can be visualized.
![Screenshot_20210424-124108_melonDS](https://user-images.githubusercontent.com/83078875/115955969-5e8cd800-a4fa-11eb-8f32-df353a3022a2.jpg)

**Comment by Flamehere** [comment] 2021-04-24 10:43
MY DEVICE IS A SAMSUNG A40

**Comment by rafaelvcaetano** [comment] 2021-04-24 14:20
Which app version are you using?

**Comment by Flamehere** [comment] 2021-04-24 14:34
Bruh 1.4.0.

**Comment by rafaelvcaetano** [comment] 2021-04-24 14:36
Then press OK and open another GitHub issue. It will include logs that will help identify the problem.

**Comment by Flamehere** [comment] 2021-04-24 14:39
When i click ok the game crash,maybe i have to download github?

**Comment by rafaelvcaetano** [comment] 2021-04-24 14:41
No. You shouldn't need anything installed. Another user also had problems reporting problems. I'll try to see what's wrong.

Meanwhile, are you using a custom BIOS? And where did you place your ROM files?

**Comment by Flamehere** [comment] 2021-04-24 14:47
I place my files in a carpet called "Roms" they are uncompressed
And i only use ds bios

**Comment by Flamehere** [comment] 2021-04-24 14:47
![Screenshot_20210424-164620_melonDS.jpg](https://user-images.githubusercontent.com/83078875/115962661-c522ed80-a51c-11eb-9815-edc7d3346d79.jpg)

**Comment by Flamehere** [comment] 2021-04-25 12:04
Bro respond pls

**Comment by rafaelvcaetano** [comment] 2021-04-25 13:00
I need you to have patience. There's nothing more that I can do right now since the error reporting is clearly not working properly. I'll try to see if I can do anything to address this for the next release.

**Comment by Flamehere** [comment] 2021-04-25 13:38
I understand you need time...
Thanks anyway

**Comment by rafaelvcaetano** [comment] 2021-04-25 22:23
Please try the [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) release. The problem most likely isn't fixed but the error reporting feature should now work. If it works, please open a new issue with the generated error.

**Comment by shabbirmahmud** [comment] 2021-04-26 06:00
Duplicate of #303

**Comment by griffi-gh** [comment] 2021-04-30 16:37
Make sure the roms aren't on SD card

**Closed** 2021-04-30 17:11 UTC
